### PR TITLE
Fixes #129 set correct type for custom date fields

### LINKED ISSUE #129: Activity 'Date' Custom Field ignores the time
To reproduce:

* Create a new custom group for Activities
* Add a field of type=Date, with a time field included (I used the 24h format).

Capture d’écran de 2019-05-06 12-35-08

Notice how the API4 explorer does not display the time field for the custom field, as it does for the `activity_date_time` field:

Capture d’écran de 2019-05-06 12-34-20

The resulting SQL query does not have the time either. This makes it difficult to find activities at a given time (I use this to detect whether a contact is busy or not for scheduling meetings).

### PR DESCRIPTION
**Pull request by colemanw**

### CODE REVIEW

**Comment by mlutfy** [comment]
hmm, I don't think this works?

From what I see, the `time_format` is not present in the `getDataType($data)`:

```
[debug] APIv4 getDataType Array(                                                                                
    [id] => 86                                                                   
    [custom_group.id] => 86                                                
    [name] => test    
    [custom_group.name] => test
    [custom_group_id] => 10                          
    [label] => test
    [data_type] => Date                                                
    [html_type] => Select Date                   
    [is_required] => 1                                     
    [is_searchable] => 1         
    [is_search_range] => 1                                                    
    [weight] => 2
    [custom_group.weight] => 2                                                    
    [is_active] => 1                                                                                                                                 
    [custom_group.is_active] => 1                                                                                                                                   
    [custom_group] => Array                                                                                                                                                        
        (                                                                       
            [name] => Test                                                     
            [id] => 10                      
        )                                                                                                   
                                                                          
)
```

Patched code:

```
$ git diff --relative .
diff --git a/Civi/Api4/Service/Spec/SpecFormatter.php b/Civi/Api4/Service/Spec/SpecFormatter.php
index c8e4d3da..17bdb9b4 100644
--- a/Civi/Api4/Service/Spec/SpecFormatter.php
+++ b/Civi/Api4/Service/Spec/SpecFormatter.php
@@ -105,7 +105,7 @@ class SpecFormatter {
    */
   private static function getDataType(array $data) {
     if (isset($data['data_type'])) {
-      return $data['data_type'];
+      return !empty($data['time_format']) ? 'Timestamp' : $data['data_type'];
     }

     $dataTypeInt = ArrayHelper::value('type', $data);
diff --git a/Civi/Api4/Service/Spec/SpecGatherer.php b/Civi/Api4/Service/Spec/SpecGatherer.php
index b1c83c89..26d9fd8d 100644
--- a/Civi/Api4/Service/Spec/SpecGatherer.php
+++ b/Civi/Api4/Service/Spec/SpecGatherer.php
@@ -92,7 +92,7 @@ class SpecGatherer {
     $extends = ($entity == 'Contact') ? ['Contact', 'Individual', 'Organization', 'Household'] : [$entity];
     $customFields = CustomField::get()
       ->addWhere('custom_group.extends', 'IN', $extends)
-      ->setSelect(['custom_group.name', 'custom_group_id', 'name', 'label', 'data_type', 'html_type', 'is_searchable', 'is_search_range', 'weight', 'is_active', 'is_view', 'option_group_id', 'default_value'])
+      ->setSelect(['custom_group.name', 'custom_group_id', 'name', 'label', 'data_type', 'html_type', 'is_searchable', 'is_search_range', 'weight', 'is_active', 'is_view', 'option_group_id', 'default_value', 'date_format', 'time_format'])
       ->execute();

     foreach ($customFields as $fieldArray) {
@@ -108,7 +108,7 @@ class SpecGatherer {
   private function getCustomGroupFields($customGroup, RequestSpec $specification) {
     $customFields = CustomField::get()
       ->addWhere('custom_group.name', '=', $customGroup)
-      ->setSelect(['custom_group.name', 'custom_group_id', 'name', 'label', 'data_type', 'html_type', 'is_searchable', 'is_search_range', 'weight', 'is_active', 'is_view', 'option_group_id', 'default_value', 'custom_group.table_name', 'column_name'])
+      ->setSelect(['custom_group.name', 'custom_group_id', 'name', 'label', 'data_type', 'html_type', 'is_searchable', 'is_search_range', 'weight', 'is_active', 'is_view', 'option_group_id', 'default_value', 'custom_group.table_name', 'column_name', 'date_format', 'time_format'])
       ->execute();

     foreach ($customFields as $fieldArray) {
```

**Comment by mlutfy** [comment]
Ah, perhaps:

in  `Civi/Api4/Service/Schema/Joinable/CustomGroupJoinable.php`

```
--- a/Civi/Api4/Service/Schema/Joinable/CustomGroupJoinable.php
+++ b/Civi/Api4/Service/Schema/Joinable/CustomGroupJoinable.php
@@ -35,7 +35,7 @@ class CustomGroupJoinable extends Joinable {
   public function getEntityFields() {
     if (!$this->entityFields) {
       $fields = CustomField::get()
-        ->setSelect(['custom_group.name', 'custom_group_id', 'name', 'label', 'data_type', 'html_type', 'is_required', 'is_searchable', 'is_search_range', 'weight', 'is_active', 'is_view', 'option_group_id', 'default_value'])
+        ->setSelect(['custom_group.name', 'custom_group_id', 'name', 'label', 'data_type', 'time_format', 'html_type', 'is_required', 'is_searchable', 'is_search_range', 'weight', 'is_active', 'is_view', 'option_group_id', 'default_value'])
         ->addWhere('custom_group.table_name', '=', $this->getTargetTable())
         ->execute();
       foreach ($fields as $field) {
```

**Comment by colemanw** [comment]
Thanks @mlutfy I've pushed up that addition.

**Comment by mlutfy** [comment]
Thank you!

**Pull request merged**
