### PR TITLE
Add save action as a bulk create/update combo.

### PR DESCRIPTION
**Pull request by colemanw**
This adds a new "save" action which combines "create" and "update". It's a very similar signature to "replace" but without the where clause as no records will be deleted.

### CODE REVIEW

**Comment by colemanw** [comment]
Depends on #193 which removes the last 'create' override.
With two actions which both create (well 3 if you count `replace`) we will need to be careful not to provide extra functionality in a "create" action class and miss out on the other two.

**Comment by eileenmcnaughton** [comment]
Yay - is this gtg?

**Comment by colemanw** [comment]
Yep.
I think this will be the go-to action for people migrating from api3 as api4 "save" is very nearly a drop-in replacement for api3 "create".

**Pull request merged**
