### PR TITLE
Add setting entity

### PR DESCRIPTION
**Pull request by colemanw**

### CODE REVIEW

**Comment by jackrabbithanna** [comment]
Yay settings as entities! This will be great for CiviCRM Entity. Hmm...methinks a APIv4 entity controller should be something on the priority list for that module.

**Comment by colemanw** [comment]
@seamuslee001 there's something odd about how CI works for extensions. I've noticed that a PR with multiple commits will have random failures, so I separated the 2 commits from this PR into 2 PRs, and individually they both passed. I think it has something to do with the way the extension gets checked out.
With core PRs jenkins will convert the PR to a patch and apply the patch to the civicrm master branch. But in the console here I see:

    Download extension (https://github.com/civicrm/org.civicrm.api4.git @ master + 20e35696f448b477b53f1e2457eb165e1e8cdaf9)

So it's not applying a patch but checking out a particular commit. I'm not sure why that causes problems, but it might have something to do with conflicts in the tree, e.g. if the tip of master is ahead of the PR branch.

**Pull request merged**
