### PR TITLE
updated phpdoc

### PR DESCRIPTION
**Pull request by Jazz-Man**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I think this repo is still subject to our whitespace standard (drupal formatting - 2 spaces :-()

**Comment by Jazz-Man** [comment]
In my work I use https://github.com/FriendsOfPHP/PHP-CS-Fixer.
here is my configuration file:
```php

return PhpCsFixer\Config::create()
    ->setUsingCache(false)
    ->setRiskyAllowed(true)
    ->setIndent('  ')
    ->setRules([
        '@Symfony' => true,
        '@Symfony:risky' => true,
        '@PHP70Migration' => true,
        '@PHP70Migration:risky' => true,
        'declare_strict_types' => false,
        'array_syntax' => ['syntax' => 'short'],
        'combine_consecutive_issets' => true,
        'combine_consecutive_unsets' => true,
        'fully_qualified_strict_types' => true,
        'is_null' => ['use_yoda_style' => true],
        'list_syntax' => ['syntax' => 'long'],
        'method_chaining_indentation' => true,
        'multiline_comment_opening_closing' => true,
        'multiline_whitespace_before_semicolons' => true,
        'no_alternative_syntax' => true,
        'no_php4_constructor' => true,
        'no_short_echo_tag' => true,
        'no_superfluous_elseif' => true,
        'no_useless_else' => true,
    ])
    ->setFinder(PhpCsFixer\Finder::create()
        ->exclude('vendor')
        ->in(__DIR__)
    )
;

/*
This document has been generated with
https://mlocati.github.io/php-cs-fixer-configurator/
you can change this configuration by importing this YAML code:

whitespace:
  indent: '  '
fixerSets:
  - '@Symfony'
  - '@Symfony:risky'
  - '@PHP70Migration'
  - '@PHP70Migration:risky'
risky: true
fixers:
  array_syntax:
    syntax: short
  combine_consecutive_issets: true
  combine_consecutive_unsets: true
  fully_qualified_strict_types: true
  is_null:
    use_yoda_style: true
  list_syntax:
    syntax: long
  method_chaining_indentation: true
  multiline_comment_opening_closing: true
  multiline_whitespace_before_semicolons: true
  no_alternative_syntax: true
  no_php4_constructor: true
  no_short_echo_tag: true
  no_superfluous_elseif: true
  no_useless_else: true

*/
```

Maybe I can fix something in the configuration to make it work for you?.
Now I have already changed the indentation parameters to 2 spaces

**Comment by Jazz-Man** [comment]
Okay, I'll make a separate configuration, because I do not work with drupal

**Comment by eileenmcnaughton** [comment]
I know it's painful :-( FWIW I wish we has adopted PSR-2

**Comment by colemanw** [comment]
This is still not quite following our standards:

- Operators should have just one space before them.
- Comments should be on their own line
- `else {` should go on a new line not after a closing `}`

**Comment by eileenmcnaughton** [comment]
but love a PR adding comments (we forget to spell that out)

**Comment by Jazz-Man** [comment]
To fix the styling of the code, I set up PHP_CodeSniffer. The instruction is taken from here https://www.drupal.org/node/1419988.
I hope that this will suit you now :)

**Comment by eileenmcnaughton** [comment]
This is the CiviCRM code sniffer plugin I think

https://github.com/civicrm/coder

For some reason the control braces in your PR as still being changed

from (correct)
```
if (condition1 || condition2) {
  action1;
}
elseif (condition3 && condition4) {
  action2;
}
else {
  defaultaction;
}
```

to (incorrect)

```
if (condition1 || condition2) {
  action1;
} elseif (condition3 && condition4) {
  action2;
} else {
  defaultaction;
}
```

https://www.drupal.org/docs/develop/standards/coding-standards#controlstruct

**Comment by colemanw** [comment]
I'm still seeing extra whitespace in the diff, e.g. multiple spaces before an `=` operator.

**Comment by Jazz-Man** [comment]
by the way, it's pretty hard for me to fix the code styling for your project. In this package https://packagist.org/packages/drupal/coder there are quite a few errors, and it not only does not fix the code, and sometimes it breaks. 
example:
1)string:
``` php
@var string, eg 'com.example.extension
```
converted to:
``` php
@var stringegcomexamplemyextension
```
2)string:
``` php
@param array|string $params
```
converted to:
``` php
@param arraystring $params
```

Often enough correction code stops when there are comments in the file:
``` php
/*
 +--------------------------------------------------------------------+
 | CiviCRM version 4.7                                                |
 +--------------------------------------------------------------------+
 | Copyright CiviCRM LLC (c) 2004-2015                                |
 +--------------------------------------------------------------------+
 | This file is a part of CiviCRM.                                    |
 |                                                                    |
 | CiviCRM is free software; you can copy, modify, and distribute it  |
 | under the terms of the GNU Affero General Public License           |
 | Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
 |                                                                    |
 | CiviCRM is distributed in the hope that it will be useful, but     |
 | WITHOUT ANY WARRANTY; without even the implied warranty of         |
 | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
 | See the GNU Affero General Public License for more details.        |
 |                                                                    |
 | You should have received a copy of the GNU Affero General Public   |
 | License and the CiviCRM Licensing Exception along                  |
 | with this program; if not, contact CiviCRM LLC                     |
 | at info[AT]civicrm[DOT]org. If you have questions about the        |
 | GNU Affero General Public License or the licensing of CiviCRM,     |
 | see the CiviCRM license FAQ at http://civicrm.org/licensing        |
 +--------------------------------------------------------------------+
 */
```

There were also a lot of minor errors that I had to correct manually :(

**Comment by colemanw** [comment]
Hey @Jazz-Man I really appreciate your contribution! Unfortunately this still is not quite right. It now appears to be using 1 tab to indent when it should be using 2 spaces.
Personally I do not use the autocorrect function of the coder module. I have my IDE set to use Drupal coding style and it does things pretty much correctly, and then I run `civilint` on the command line before committing just to make sure.

**Comment by colemanw** [comment]
FYI We do not use the autoformat function. As you noted it messes up more than it fixes.

In general the way we keep the code style consistent is to set our IDE to use Drupal coding standards, and before committing run the command `civilint` to ensure there are no code style regressions.

While I really appreciate your contribution I'm going to close it as it's not currently mergable.

**Pull request closed without merging**
