### PR TITLE
Use metadata to set default where clause for get actions

### PR DESCRIPTION
**Pull request by colemanw**
The upshot of this PR is that `is_deleted` contacts will be excluded from `Get()` by default, and it's done in a way that will be easily extensible for other entities and fields.

- Removes `default_value` from all fields in getFields except for `create` operations.
- Then we can assume that any field defaults in `get` operations are there on purpose and we add them to the where clause.
- Defaults are *not* added to the where clause if fetching records by id or if the field is already part of the clause.
- Removes the previous half-baked attempt to exclude `is_test` participants.
- Adds default to `is_deleted` contacts.
- Adds tests.

See https://lab.civicrm.org/dev/core/issues/1062

### CODE REVIEW

**Comment by colemanw** [comment]
I've revised this PR to only exclude `is_deleted` contacts and will save the more tricky issue of `is_test` contributions,participants,memberships,etc. for a followup pr/discussion.

**Comment by mattwire** [comment]
@colemanw I feel like this would be better introducing a generic default for `is_deleted` rather than just on one entity, otherwise we'll end up in a situation like api3 where different entities have different/inconsistent defaults - which is a real pain!

**Comment by colemanw** [comment]
@mattwire gooooood point. I forgot about deleted activities and cases!
Ok that's a good case for making a generic isDeletedFieldSpecProvider that runs on every entity.

**Comment by colemanw** [comment]
@mattwire ok I've rebased this now, adding the file Civi/Api4/Service/Spec/Provider/GetActionDefaultsProvider.php

**Comment by mattwire** [comment]
@colemanw :-) Happy with this now from a concept POV - I've not actually tested it though!

**Comment by colemanw** [comment]
That's ok, that's what unit tests are for :)

**Pull request merged**
