### PR TITLE
Added all possible Entity

### PR DESCRIPTION
**Pull request by Jazz-Man**

### CODE REVIEW

**Comment by Jazz-Man** [comment]
Unfortunately I can not run PHPUnit tests :(
First of all I work in WordPress environment. Second, cv does not support wp environment. And I do not have much time to write individual tests that can be run in the Wordpress work environment.

**Comment by colemanw** [comment]
Ok, could you please:

- revert your changes to the existing files and only add new files in this PR
- rebase this PR into a single commit

and I'll see about getting the unit tests running with it.

**Comment by colemanw** [comment]
@civicrm-builder test this please

**Comment by colemanw** [comment]
@civicrm-builder add to whitelist

**Comment by colemanw** [comment]
We are working on adding entities in smaller chunks to be mindful of tests.

**Pull request closed without merging**
