### PR TITLE
Add location type entity

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw I can enable some tests in core once this is merged

**Comment by eileenmcnaughton** [comment]
out of interest is there a better way in apiv4 to do this

```
    $locationExists = LocationType::get()
      ->addWhere('name', '=', 'Old_2019')
      ->selectRowCount()
      ->execute()
      ->count();
    if (!$locationExists) {
      LocationType::create()
        ->addValue('name','Old_2019')
        ->addValue('display_name', 'Old 2019')
        ->addValue('description', 'Address on file in 2019 before TargetSmart update  ')
        ->execute();
    }
```

**Comment by colemanw** [comment]
> out of interest is there a better way in apiv4 to do this
> 
> ```
>     $locationExists = LocationType::get()
>       ->addWhere('name', '=', 'Old_2019')
>       ->selectRowCount()
>       ->execute()
>       ->count();
>     if (!$locationExists) {
>       LocationType::create()
>         ->addValue('name','Old_2019')
>         ->addValue('display_name', 'Old 2019')
>         ->addValue('description', 'Address on file in 2019 before TargetSmart update  ')
>         ->execute();
>     }
> ```

You're asking if there's a way to do "create if not exists" and my answer is "yes but not yet." I've got it in my head to do a "save" action which could work like:

    LocationType::save()
      ->setMatchingField('name')
      ->addRecord([
        'name' => 'Old_2019',
        'display_name' => 'Old 2019',
        'description' =>  'Address on file in 2019 before TargetSmart update,
      )->execute();

**Comment by eileenmcnaughton** [comment]
cool

**Comment by eileenmcnaughton** [comment]
Also related https://github.com/civicrm/civicrm-core/pull/14975

**Pull request merged**
