### PR TITLE
Update Api4SelectQuery.php

### PR DESCRIPTION
**Pull request by Jazz-Man**
Added ability to select all fields from a joined table:
for example:
```php
use Civi\Api4\Contact;

try {
    $membership = Contact::get()
      ->setSelect([
        'addresses.*',
        'phones.*',
        'websites.*',
        'emails.*',
        'uf_matchs.*',
        'relationships.*',
        'memberships.*'
      ])
      ->addWhere('uf_matchs.uf_id', 'IS NOT NULL', true)
      ->setLimit(1)
                         ->execute();
} catch (Exception $e) {
    var_dump($e->getMessage());
}


var_dump($membership);

```
result:
```php

Civi\Api4\Generic\Result {#961
  +entity: "Contact"
  +action: "get"
  +version: 4
  flag::STD_PROP_LIST: false
  flag::ARRAY_AS_PROPS: false
  iteratorClass: "ArrayIterator"
  storage: array:1 [
    0 => array:8 [
      "id" => "210"
      "addresses" => []
      "phones" => array:1 [
        0 => array:10 [
          "id" => "484"
          "contact_id" => "210"
          "location_type_id" => "1"
          "is_primary" => "1"
          "is_billing" => "0"
          "mobile_provider_id" => null
          "phone" => "123456789"
          "phone_ext" => null
          "phone_numeric" => "123456789"
          "phone_type_id" => "1"
        ]
      ]
      "websites" => []
      "emails" => array:1 [
        0 => array:12 [
          "id" => "182"
          "contact_id" => "210"
          "location_type_id" => "1"
          "email" => "mail2@mail.com"
          "is_primary" => "1"
          "is_billing" => "0"
          "on_hold" => "0"
          "is_bulkmail" => "0"
          "hold_date" => null
          "reset_date" => null
          "signature_text" => null
          "signature_html" => null
        ]
      ]
      "uf_matchs" => array:1 [
        0 => array:6 [
          "id" => "636"
          "domain_id" => "1"
          "uf_id" => "11"
          "uf_name" => "mail1@mail.com"
          "contact_id" => "210"
          "language" => null
        ]
      ]
      "relationships" => array:1 [
        0 => array:11 [
          "id" => "72"
          "contact_id_a" => "210"
          "contact_id_b" => "367"
          "relationship_type_id" => "5"
          "start_date" => null
          "end_date" => null
          "is_active" => "1"
          "description" => ""
          "is_permission_a_b" => "1"
          "is_permission_b_a" => "0"
          "case_id" => null
        ]
      ]
      "memberships" => array:1 [
        0 => array:16 [
          "id" => "522"
          "contact_id" => "210"
          "membership_type_id" => "4"
          "join_date" => "2017-05-01"
          "start_date" => "2017-05-01"
          "end_date" => "2018-04-30"
          "source" => "Website"
          "status_id" => "2"
          "is_override" => null
          "status_override_end_date" => null
          "owner_membership_id" => "227"
          "max_related" => null
          "is_test" => "0"
          "is_pay_later" => "0"
          "contribution_recur_id" => null
          "campaign_id" => null
        ]
      ]
    ]
  ]
}


```

### CODE REVIEW

**Comment by colemanw** [comment]
Hey @Jazz-Man this is great. Could you please update the unit test as well? Let me know if you have any questions about that.

**Comment by Jazz-Man** [comment]
I will add a few unit tests as soon as I have a little more time:)

**Comment by colemanw** [comment]
Hey @Jazz-Man are you still around? It would be great to get this change merged in.

**Comment by Jazz-Man** [comment]
Hi friends:)
I'm no longer working on a project in which I used civicrm.
But on the next weekend, I can complete all my PRs

**Comment by JoeMurray** [comment]
That would be very generous. Thank you!

**Comment by Jazz-Man** [comment]
@colemanw  Yes, I closed this PR but I will open it again, but already in another branch. I also benefited greatly from this change.

**Pull request closed without merging**
